CREATE TABLE IF NOT EXISTS reserved_slugs (
    slug TEXT PRIMARY KEY,
    reason TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO reserved_slugs (slug, reason) VALUES
('www', 'System default'),
('api', 'System default'),
('admin', 'System default'),
('app', 'System default'),
('mail', 'System default'),
('ftp', 'System default'),
('cdn', 'System default'),
('static', 'System default'),
('assets', 'System default'),
('media', 'System default'),
('auth', 'System default'),
('login', 'System default'),
('signup', 'System default'),
('register', 'System default'),
('teacher', 'System default'),
('teachers', 'System default'),
('student', 'System default'),
('students', 'System default'),
('principal', 'System default'),
('support', 'System default'),
('help', 'System default'),
('status', 'System default'),
('blog', 'System default'),
('docs', 'System default'),
('dashboard', 'System default'),
('account', 'System default'),
('accounts', 'System default'),
('billing', 'System default'),
('pay', 'System default'),
('payment', 'System default'),
('payments', 'System default'),
('webhook', 'System default'),
('webhooks', 'System default'),
('socket', 'System default'),
('ws', 'System default'),
('wss', 'System default'),
('live', 'System default'),
('streaming', 'System default'),
('video', 'System default'),
('videos', 'System default'),
('course', 'System default'),
('courses', 'System default'),
('institute', 'System default'),
('institutes', 'System default'),
('lms', 'System default'),
('platform', 'System default'),
('shikkhabhumi', 'System default'),
('www2', 'System default'),
('staging', 'System default'),
('dev', 'System default'),
('test', 'System default'),
('preview', 'System default'),
('null', 'System default'),
('undefined', 'System default')
ON CONFLICT (slug) DO NOTHING;
