const videoService = require('../services/videoService');

class VideoController {
    async listVideos(req, res) {
        try {
            const userId = req.user.id;
            const role = req.user.role;
            let videos;

            if (role === 'teacher') {
                 // Teacher sees videos they own
                 videos = await videoService.getManagedVideos(userId);
            } else {
                 // Student sees videos they have permission for
                 videos = await videoService.getAvailableVideos(userId);
            }
            res.json(videos);
        } catch (error) {
            console.error('Error listing videos:', error);
            res.status(500).json({ error: 'Internal server error' });
        }
    }

    async getSignedUrl(req, res) {
        try {
            const { videoId } = req.params;
            const userId = req.user.id; // From authMiddleware

            const signedUrl = await videoService.getSignedVideoUrl(userId, videoId);
            res.json({ url: signedUrl });
        } catch (error) {
            console.error('Error getting signed URL:', error);
            if (error.message === 'Access denied') {
                return res.status(403).json({ error: 'Access denied' });
            }
            if (error.message === 'Video not found') {
                return res.status(404).json({ error: 'Video not found' });
            }
            res.status(500).json({ error: 'Internal server error' });
        }
    }

    async getKey(req, res) {
        try {
            // Support both 'vid' (legacy/docs) and 'id' (generated by ffmpeg)
            const vid = req.query.vid || req.query.id;
            const userId = req.user.id;

            if (!vid) {
                return res.status(400).json({ error: 'Missing video ID (vid or id)' });
            }

            const key = await videoService.getVideoKey(userId, vid);

            res.set('Content-Type', 'application/octet-stream');
            res.send(key);
        } catch (error) {
            console.error('Error getting key:', error);
            if (error.message === 'Access denied') {
                return res.status(403).send('No access');
            }
            if (error.message === 'Key file not found') {
                return res.status(404).send('Key not found');
            }
            res.status(500).send('Internal server error');
        }
    }
}

module.exports = new VideoController();
